services:
#  account-service:
#    container_name: account-service
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#    environment:
#      - "ASPNETCORE_ENVIRONMENT=Development"
#      - "Jwt:Authority=http://keycloak:8080/realms/myrealm"
#      - "Jwt:Audience=account"
#    networks:
#      - app-network
#    # Сервис запустится только после того, как keycloak будет в состоянии "healthy"
#    depends_on:
#      keycloak:
#        condition: service_healthy
  keycloak:
    container_name: keycloak
    # Используем официальный образ Keycloak
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      # Логин и пароль для админ-панели Keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Файл realm-export.json должен лежать в папке ./keycloak-config
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge